### ISSUE TITLE
S37

### ISSUE THREAD

**Issue by davidefer** [nxyd/srecord#4]
Hi
could you please add the extension *.s37 as accepted file? That would be great.
Thanks in advance

**Comment by PavolAstrab** [comment]
Hello,
It would be nice if developers themselves have the possibility to add/customize extensions of Motorola files to be sensitive for your VSC extension. There are many different file extensions of these kinds of files - see the right block on the page https://en.wikipedia.org/wiki/SREC_(file_format) - there are listed.

**Comment by nxyd** [comment]
Sorry to response you so late, this is released in 0.0.4.
