### ISSUE TITLE
address range limitation

### ISSUE THREAD

**Issue by MattBelle95** [nxyd/srecord#8]
When the size is larger than 31 bits, the extension does not decode the address 
![image](https://user-images.githubusercontent.com/20547175/185923054-7b5dd182-3780-48bf-86b9-ba8fb6394926.png)
the first 3 lines, the tool is able to decode the address, but not the last 3 lines

**Comment by nxyd** [comment]
This will be fixed in next version 0.0.5.

**Comment by MattBelle95** [comment]
thanks
